#+TITLE:      系统参数配置 
#+AUTHOR:      Xuancong Lee 
#+EMAIL:       congleetea@gmail.com
#+DATE:        2017-04-25 Tue 
#+URI:         /blog/%y/%m/%d/系统参数配置
#+KEYWORDS:    ops,system tuning
#+TAGS:        ops
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 服务器参数配置 

* 几个文件
系统参数配置常常涉及到下面这几个文件和目录，通过
[[http://www.jianshu.com/p/20a2dd80cbad][ulimit、limits.conf、sysctl和proc文件系统]]

总体来说ulimit时一个linux的程序，负责设置和查看系统的限制信息，而sysctl也是一个linux的
程序，可以在内核运行时动态修改内核的运行参数，可用的内核参数在目录/proc/sys中。

就生效作用来看，在shell中使用ulimit或者sysctl设置的，只在该shell进程和其子进程中有效，
不改变其他进程的系统配置。如果要长久生效，可以修改对应配置文件，这样启动之后时永久生效的。

配置文件的路径可以再/etc下面，这是对所有用户有效的；也可以在~/.bash_profile中，这只对当前
用户永久生效。再控制台设置就只对当前进程有效。也可以放在程序的启动脚本中，这样只对该程序
有效。
默认的配置文件分别时/etc/security/limits.conf和/etc/sysctl.conf中。

关于/proc的详细讲解可以参考[[https://www.ibm.com/developerworks/cn/linux/l-proc.html][使用 /proc 文件系统来访问 Linux 内核的内容]] 。





* 注意
a.    所有进程打开的文件描述符数不能超过/proc/sys/fs/file-max

b.    单个进程打开的文件描述符数不能超过user limit中nofile的soft limit

c.    nofile的soft limit不能超过其hard limit

d.    nofile的hard limit不能超过/proc/sys/fs/nr_open

* 文件配置

** sudo echo 2097152 > /proc/sys/fs/nr_open

** /etc/sysctl.conf:

#+BEGIN_SRC text
  vm.swappiness = 0
  net.core.somaxconn = 32767
  net.core.netdev_max_backlog = 16384
  net.core.rmem_default=262144
  net.core.wmem_default=262144
  net.core.rmem_max=16777216
  net.core.wmem_max=16777216
  net.core.optmem_max=16777216
  # reuse port http://zyan.cc/post/271/ 
  net.ipv4.ip_local_port_range= 1000 65535
  net.ipv4.tcp_max_syn_backlog = 16384
  net.ipv4.neigh.default.gc_stale_time=120
  net.ipv4.conf.all.rp_filter=0
  net.ipv4.conf.default.rp_filter=0
  net.ipv4.conf.default.arp_announce = 2
  net.ipv4.conf.all.arp_announce=2
  net.ipv4.tcp_syncookies = 1
  net.ipv4.tcp_max_syn_backlog = 1024
  net.ipv4.tcp_synack_retries = 2
  net.ipv4.conf.lo.arp_announce=2
  net.ipv4.tcp_max_tw_buckets=1048576
  net.ipv4.tcp_fin_timeout = 15
  net.ipv4.tcp_timestamps=1
  net.ipv4.tcp_tw_recycle=1
  net.ipv4.tcp_tw_reuse = 1
  net.ipv4.tcp_rmem= 4096 16777216
  net.ipv4.tcp_wmem= 4096 16777216
  net.ipv6.conf.all.disable_ipv6 = 1
  net.ipv6.conf.default.disable_ipv6 = 1
  net.ipv6.conf.lo.disable_ipv6 = 1
  net.nf_conntrack_max=1000000
  net.netfilter.nf_conntrack_max=1000000
  net.netfilter.nf_conntrack_tcp_timeout_time_wait=30

  fs.file-max = 2097152
  fs.nr_open = 2097152
#+END_SRC


** /etc/security/limits.conf:

#+BEGIN_SRC text
 *      soft   nofile      1048576
 *      hard   nofile      1048576
#+END_SRC

* 执行生效
执行 sysctl -p
检验ulimit -n


* 常用指令

